project:
  type: website
  output-dir: docs
  
website:
  title: "Curso sociolog√≠a"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/molivaolave
      - icon: github
        href: https://github.com/moliva-sociologia/template001
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Marcelo Oliva Olave"

format:
  html:
    theme: cerulean
    toc: true

editor: source

